@startuml
title Получение события от системы-отправителя

autonumber

participant "Система-отправитель" as Sender
participant "idempotency_service" as IdemService
database "База данных" as DB

Sender -> IdemService: Отправка Kafka события
note right of Sender #FFFFFF
[topic_name]
{
  "headers": {
    "idempotencyKey"": "550e8400-e29b-41d4-a716-446655440000",
    // any
  },
  "payload": {
    // any
  }
}
end note

IdemService -> IdemService: Валидация события

alt #tomato Отсутствует тело запроса / header [idempotencyKey]
    IdemService -> IdemService: Завершить процесс
end


IdemService -> DB: Найти idempotency
note right of DB #FFFFFF
    SELECT EXISTS (
        SELECT 1
        FROM idempotency
        WHERE integration_flow = [integration_flow] из памяти сервиса
          AND integration_operation = [integration_operation] из памяти сервиса
          AND idempotency_key = [headers.idempotencyKey] из запроса
    )
end note
DB --> IdemService: Результат поиска

IdemService -> IdemService: Найти связанный топик ответа системе-отправителю\n [request_out] по [integration_flow] и [integration_operation]
note right of IdemService #FFFFFF
    Аналитическая переменная (в памяти сервиса): [request_out]
end note

alt #tomato Запись найдена

    alt #tomato request_out существует
            IdemService -> DB: Создать kafka_event_outbox
            note right of DB #FFFFFF
               kafka_event_outbox.result = SUCCESS
               kafka_event_outbox.result_description = «Событие успешно получено»
               kafka_event_outbox.integration_flow = [integration_flow] из памяти сервиса
               kafka_event_outbox.integration_operation = [integration_operation] из памяти сервиса
               kafka_event_outbox.status = NEW
               kafka_event_outbox.create_date = текущее время [UTC +3:00]
               kafka_event_outbox.update_date = текущее время [UTC +3:00]
            end note
        end

    IdemService -> DB: Создать kafka_event_outbox
    note right of DB #FFFFFF
       kafka_event_outbox.result = FAIL
       kafka_event_outbox.result_description = «Событие не прошло проверку на идемпотентность»
       kafka_event_outbox.integration_flow = [integration_flow] из памяти сервиса
       kafka_event_outbox.integration_operation = [integration_operation] из памяти сервиса
       kafka_event_outbox.status = NEW
       kafka_event_outbox.create_date = текущее время [UTC +3:00]
       kafka_event_outbox.update_date = текущее время [UTC +3:00]
    end note
else #yellowgreen Запись не найдена

    alt #yellowgreen request_out существует
        IdemService -> DB: Создать kafka_event_outbox
        note right of DB #FFFFFF
           kafka_event_outbox.result = SUCCESS
           kafka_event_outbox.result_description = «Событие успешно получено»
           kafka_event_outbox.integration_flow = [integration_flow] из памяти сервиса
           kafka_event_outbox.integration_operation = [integration_operation] из памяти сервиса
           kafka_event_outbox.status = NEW
           kafka_event_outbox.create_date = текущее время [UTC +3:00]
           kafka_event_outbox.update_date = текущее время [UTC +3:00]
        end note
    end

    IdemService -> DB: Создать idempotency
    note right of DB #FFFFFF
       idempotency.idempotency_key = [headers.idempotencyKey] из запроса
       idempotency.integration_flow = [integration_flow] из памяти сервиса
       idempotency.integration_operation = [integration_operation] из памяти сервиса
       idempotency.status = RESERVED
       idempotency.status_description = null
       idempotency.create_date = текущее время [UTC +3:00]
       idempotency.update_date = текущее время [UTC +3:00]
       idempotency.payload = [payload] из запроса
       idempotency.headers = [headers] из запроса кроме "idempotencyKey"
    end note
    IdemService -> IdemService: Завершить процесс
end

@enduml