@startuml
title Отправка события системе-получателю

autonumber

participant "idempotency_service" as IdemService
database "База данных" as DB
participant "Система-получатель" as Receiver

loop send_request_fixed_delay

    IdemService -> DB : IdempotencyRepository.lockNextReserved()
    note right of DB #FFFFFF
        Получить первую запись idempotency
        со status = RESERVED
    end note

    DB --> IdemService : Результат поиска

    alt #yellowgreen Запись не найдена
        IdemService -> IdemService : Завершить процесс

    else #yellowgreen Запись найдена

        IdemService -> IdemService : Взять [reply_in] из idempotency.yaml_snapshot

        note right of IdemService #FFFFFF
            reply_in = [idempotency.yaml_snapshot.reply_in]
        end note

        alt reply_in существует

            IdemService -> Receiver : Отправить событие системе-получателю
            note right of Receiver #FFFFFF
                Отправка события в [reply_in]
                {
                  "headers": {
                    "globalKey": "[idempotency.global_key]",
                    "uid": "[idempotency.source_uid]",
                    "service": "[idempotency.service_name]",
                    "integration": "[idempotency.integration_name]",
                    [idempotency.headers]
                  },
                  "payload": {
                    [idempotency.payload]
                  }
                }
            end note

            Receiver --> IdemService : Получение ответа

            alt Событие успешно отправлено
                IdemService -> IdemService : Взять [reply_out] из idempotency.yaml_snapshot
                note right of IdemService #FFFFFF
                    reply_out = [idempotency.yaml_snapshot.reply_out]
                end note

                alt reply_out существует
                    IdemService -> DB : IdempotencyRepository.markWaitingAsyncResponse(operation)
                    note right of DB #FFFFFF
                        idempotency.status = WAITING_ASYNC_RESPONSE
                        idempotency.update_date = текущее время [UTC +3:00]
                    end note
                    IdemService -> IdemService : Завершить процесс

                else reply_out не существует
                    IdemService -> DB : IdempotencyRepository.markCommitted(operation)
                    note right of DB #FFFFFF
                        idempotency.status = COMMITTED
                        idempotency.update_date = текущее время [UTC +3:00]
                    end note
                    IdemService -> IdemService : Завершить процесс
                end
            else #tomato Ошибка отправки
                alt Временная ошибка отправки
                    note right of IdemService #FFFFFF
                        KafkaException
                        TimeoutException
                        NetworkException
                        DisconnectException
                        LeaderNotAvailableException
                        RetriableException
                    end note

                    IdemService -> IdemService : Завершить процесс

                else #tomato Иная ошибка отправки
                    IdemService -> DB : IdempotencyRepository.markError(operation)
                    note right of DB #FFFFFF
                        idempotency.status = ERROR
                        idempotency.status_description = "Произошла ошибка при отправке события системе-получателю в [reply_in]: [java.exception]"
                        idempotency.update_date = текущее время [UTC +3:00]
                    end note
                    IdemService -> IdemService : Завершить процесс
                end
            end

        else #tomato reply_in не существует

            IdemService -> DB : IdempotencyRepository.markError(operation)
            note right of DB #FFFFFF
                idempotency.status = ERROR
                idempotency.status_description = "Не найден канал reply_in в сохранённом yaml_snapshot"
                idempotency.update_date = текущее время [UTC +3:00]
            end note

            IdemService -> IdemService : Завершить процесс
        end
    else #tomato Внутренняя ошибка
        IdemService -> IdemService : Завершить процесс
    end
end
@enduml
